-- MySQL Script generated by MySQL Workbench
-- Sun Jun  4 23:59:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema projeto_usu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projeto_usu` ;

-- -----------------------------------------------------
-- Schema projeto_usu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_usu` DEFAULT CHARACTER SET utf8 ;
USE `projeto_usu` ;

--
-- Estrutura da tabela `perfil`
--

CREATE TABLE `perfil` (
  `id_perfil` int(11) NOT NULL,
  `nome_perfil` varchar(45) NOT NULL,
    PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Extraindo dados da tabela `perfil`
--

INSERT INTO `perfil` (`id_perfil`, `nome_perfil`) VALUES
(1, 'Administrador'),
(2, 'Cliente'),
(3, 'Moderador');

-- --------------------------------------------------------

-- -----------------------------------------------------
-- Table `projeto_usu`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine_community`.`usuario` ;

CREATE TABLE `usuario` (
  `id_usuario` int(11) NOT NULL,
  `nome_usu` varchar(100) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `senha` varchar(50) DEFAULT NULL,
  `telefone` varchar(20) DEFAULT NULL,
  `cpf` varchar(14) DEFAULT NULL,
  `sexo` varchar(12) DEFAULT NULL,
  `dt_nascimento` date DEFAULT NULL,
  `endereco` varchar(70) DEFAULT NULL,
  `numero` char(7) DEFAULT NULL,
  `complemento` varchar(15) DEFAULT NULL,
  `bairro` varchar(70) DEFAULT NULL,
  `cidade` varchar(70) DEFAULT NULL,
  `cep` char(9) DEFAULT NULL,
  `uf` char(2) DEFAULT NULL,
  `foto` varchar(50) DEFAULT NULL,
  `situacao` varchar(10) DEFAULT 'Ativo' COMMENT 'Ativo\\nCancelado\\nBloqueado',
  `fk_id_perfil` int(11) NOT NULL,
  PRIMARY KEY (`id_usuario`, `fk_id_perfil`),
  INDEX `fk_usuario_perfil_usu1_idx` (`fk_id_perfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil_usu1`
    FOREIGN KEY (`fk_id_perfil`)
    REFERENCES `cine_community`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) 
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Extraindo dados da tabela `usuario`
--

INSERT INTO `usuario` (`id_usuario`, `nome_usu`, `email`, `senha`, `telefone`, `cpf`, `sexo`, `dt_nascimento`, `endereco`, `numero`, `complemento`, `bairro`, `cidade`, `cep`, `uf`, `foto`, `situacao`, `fk_id_perfil`) VALUES
(1, 'Administrador', 'adm@email.com', md5('123'), '(61)77777-6565', '000.000.888-99', 'Masculino', '1989-03-10', 'QNM 11', '11', 'Casa', 'CEILANDIA NORTE', 'BrasÃ­lia', '72211-111', 'DF', NULL, 'Ativo', 1),
(2, 'JosÃ© do Teste', 'jose@email.com', md5('123456'), '6198887-0909', '333.444.777-77', 'Feminino', '2000-02-01', 'QSC 01 AREA ESP ', '444', 'Ap', 'CEILANDIA NORTE', 'BRASILIA', '72-999-02', 'MG', NULL, 'Ativo', 2),
(2, 'JosÃ© do Teste', 'jose@email.com', md5('123456'), '6198887-0909', '333.444.777-77', 'Feminino', '2000-02-01', 'QSC 01 AREA ESP ', '444', 'Ap', 'CEILANDIA NORTE', 'BRASILIA', '72-999-02', 'MG', NULL, 'Ativo', 3);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
